dependencies:
  - name: jenkins
    version: 0.10.7
    repository: http://chartmuseum.build.cd.jenkins-x.io
  - name: pipelines
    version: 0.0.1
    repository: file://pipelines
  - name: exposecontroller
    version: 2.3.50
    repository: http://chartmuseum.build.cd.jenkins-x.io
    alias: expose
  - name: exposecontroller
    version: 2.3.50
    repository: http://chartmuseum.build.cd.jenkins-x.io
    alias: cleanup
  - name: pipelinecontroller
    version: 0.0.1
    repository: file://pipelinecontroller
  - name: chartmuseum
    version: 0.3.2
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  - name: nexus
    version: 0.0.4
    repository: http://chartmuseum.build.cd.jenkins-x.io
  - name: heapster
    version: 0.2.4
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: kubernetes-dashboard
    version: 0.4.4
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: monocular
    version: 0.5.0
    repository: https://kubernetes-helm.github.io/monocular
  - name: docker-registry
    version: 1.0.1
    repository: https://kubernetes-charts.storage.googleapis.com
