dependencies:
  # - name: jenkins
  #   version: 0.9.0
  #   repository: https://kubernetes-charts.storage.googleapis.com
  - name: jenkins
    version: 0.10.6
    repository: http://chartmuseum.thunder.thunder.fabric8.io
  - name: pipelines
    version: 0.0.1
    repository: file://pipelines
  - name: exposecontroller
    version: 0.1.3
    repository: http://chartmuseum.cd.thunder.fabric8.io
    alias: expose
  - name: exposecontroller
    version: 0.1.3
    repository: http://chartmuseum.cd.thunder.fabric8.io
    alias: cleanup
  - name: pipelinecontroller
    version: 0.0.1
    repository: file://pipelinecontroller
  - name: chartmuseum
    version: 0.1.3
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  - name: sonatype-nexus
    version: 0.1.5
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: heapster
    version: 0.2.4
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: kubernetes-dashboard
    version: 0.4.4
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: monocular
    version: 0.5.0
    repository: https://kubernetes-helm.github.io/monocular
  - name: docker-registry
    version: 1.0.1
    repository: https://kubernetes-charts.storage.googleapis.com