apiVersion: v1
data:
{{- if .Values.PipelineSecrets.GitCreds }}
  credentials: {{ .Values.PipelineSecrets.GitCreds | b64enc | quote }}
{{- else }}
  credentials: ""
{{- end }}
kind: Secret
metadata:
  name: jenkins-git-credentials
type: Opaque