apiVersion: v1
data:
{{- if .Values.PipelineSecrets.Netrc }}
  .netrc: {{ .Values.PipelineSecrets.Netrc | b64enc | quote }}
{{- else }}
  .netrc: ""
{{- end }}
kind: Secret
metadata:
  name: jenkins-netrc
type: Opaque